version: '3'
services:
  db:
    image: mongo
    restart: always
    command: '--quiet'
    ports:
      - "27017:27017"
  server:
    image: 'node:11-alpine'
    user: 'node'
    working_dir: /home/node/app
    environment:
      NODE_ENV: development
      DB_HOST: db
    volumes:
      - ./:/home/node/app
    ports:
      - "3012:3012"
    depends_on:
      - db
    links:
      - "db:db"
    command: "node ./server.js"
